Repository WCY-dt/EasyTransfer, pull requests merged in 2025-03, with the labels that each got.

#69 Fix typos
  README.md
  README_ZH-cn.md
Labels: documentation

#72 fix: Fixed the issue where auto download is disabled in certain browsers
  CHANGELOG.md
  client/package-lock.json
  client/package.json
  client/src/components/ReceiveItem.vue
Labels: bug

#74 fix: Fix issues relate to connection
  CHANGELOG.md
  SECURITY.md
  client/package-lock.json
  client/package.json
  client/src/const.ts
  client/src/stores/connect.ts
  client/src/stores/setting.ts
  package-lock.json
  package.json
  server/server.ts
Labels: bug, enhancement

#75 Doc: Update README_ZH-cn.md
  README_ZH-cn.md
Labels: documentation

#78 feat: Using @mdi/js instead of webfont
  CHANGELOG.md
  client/package-lock.json
  client/package.json
  client/src/assets/main.css
  client/src/components/FooterModal.vue
  client/src/components/HeaderModal.vue
  client/src/components/OperationId.vue
  client/src/components/ReceiveItem.vue
  client/src/components/ReceiveModal.vue
  client/src/components/SendItem.vue
  client/src/components/SendModal.vue
  client/src/components/SettingsModal.vue
  client/src/components/UploadFile.vue
  client/src/components/UploadPhoto.vue
  client/src/components/UploadText.vue
  client/src/shims-vue.d.ts
  client/src/utils/msgType.ts
Labels: bug, enhancement
